name: QA Basic Check

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  check-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Verify readme.txt exists
      run: |
        if [ ! -f readme.txt ]; then
          echo "readme.txt not found!"
          exit 1
        fi

    - name: Check for keyword "QA" in readme.txt
      run: |
        if ! grep -q "QA" readme.txt; then
          echo "Keyword 'QA' not found in readme.txt!"
          exit 1
        else
          echo "Keyword 'QA' found!"
        fi
